### ISSUE TITLE
几个“不存在用户定义的”的报错

### ISSUE THREAD

**Issue by DC0212** [kc345ws/FatigueMonitoring#1]
问题已解决啦，您的代码给了我很大的启发，谢谢！

**Comment by xql5891129** [comment]
不存在用户定义的从 "cv::Rect" 到 "CvRect" 的适当转换	怎么回事

**Comment by peng513** [comment]
> 不存在用户定义的从 "cv::Rect" 到 "CvRect" 的适当转换 怎么回事

您好！您这个问题解决了嘛？谢谢
